spring:
# Resource bundle (Internationalization)
  messages:
    basename: i18n.messages
    encoding: UTF-8
    fallback-to-system-locale: true
    use-code-as-default-message: false

  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:file:~/default
      username: sa
      password:
      driverClassName: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${YOUR_CLIENT_SECRET}
            client-secret: ${YOUR_CLIENT_ID}
            redirect-uri: https://www.getpostman.com/oauth2/callback
            scope: openid profile email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

